schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "02-conveyor-belt"
owner:
  username: "RosaMirandaJ"
  id: 252872209
  accepted_at: "2026-09-08T10:18:03Z"
source:
  owner: "indprog"
  owner_id: 316953525
  repo: "python-template"
  branch: "main"
